name = "cookbook"
version = "1.0.0"
target = "javascript"

[dependencies]
envoy = ">= 1.0.2 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gsv = ">= 3.0.0 and < 4.0.0"
lustre = ">= 4.4.4 and < 5.0.0"
simplifile = ">= 2.1.0 and < 3.0.0"
tom = ">= 1.1.0 and < 2.0.0"
xmb = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
