name = "cookbook"
version = "1.0.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.45.0 and < 2.0.0"
youid = ">= 1.2.0 and < 2.0.0"
argus = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
